---
kind: pipeline
name: front-end

steps:
  - name: test
    image: node:12
    commands:
      - cd front-end
      - npm install
      - npm test

---
kind: pipeline
name: back-end

steps:
  - name: test
    image: node:12
    commands:
      - cd back-end
      - npm install
      - npm test
