---
kind: pipeline
name: front-end

steps:
  - name: test
    image: node:12
    commands:
      - cd front-end
      - npm install
      - npm test

---
kind: pipeline
name: back-end

steps:
  - name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    ver: 1.0
    timeout: 20
    sources: ./back-end

  - name: test
    image: node:12
    commands:
      - cd back-end
      - npm install
      - npm test



