version: '3.6'

services:
  # Mongo
  bookstore_mongo:
    image: mongo
    container_name: bookstore_mongo
    networks:
      bookstore:
        aliases:
        - bookstore_mongo
    ports:
      - 27017:27017

  # Back-end
  backend_bookstore:
    build:
      context: ./back-end
    image: bookstore-backend:10
    networks:
      - bookstore
    volumes:
      - ./back-end:/back-end
    depends_on:
      - bookstore_mongo
    ports:
      - 3000:3000
    env_file: back-end/app.env
    container_name: bookstore_backend
    restart: always
    command: sh -c "/wait-for bookstore_mongo:27017 -t 0 && npm start"

  # Back-end
  frontend_bookstore:
    build:
      context: ./front-end
    image: bookstore:1.0
    networks:
      - bookstore
    depends_on:
      - bookstore_mongo
      - backend_bookstore
    ports:
      - 8000:80
    container_name: bookstore_frontend

networks:
  bookstore:
