import { Book } from "../books/book";

export const BOOKS: Book[] = [
  {id: 1, title: 'Double The Trouble', category: 'Drama', desc: 'After all that I had been through with Anita, I never thought that I would go though it ever again. I thought I had learned a valuable lesson and that no person would ever be able to get over on me again. Little did I know that not only would I go through it again but I would go through it with double the trouble.'},
  {id: 2, title: 'Rope: A play', category: 'Drama', desc: 'For the mere sake of adventure, danger, and the "fun of the thing," Wyndham Brandon persuades his weak minded friend, Charles Granillo, to assist him in the murder of a fellow undergraduate, a perfectly harmless man named Ronald Raglan. They place the body in a wooden chest, and to add spice to their handiwork, invite a few acquaintances, including the dead youth\'s father, to a party, the chest with its gruesome contents serving as a supper table. The horror and tension are worked up gradually; thunder grows outside, the guests leave, and we see the reactions of the two murderers, watched closely by the suspecting lame poet, Rupert Cadell. Finally they break down under the strain and confess their guilt.'},
  {id: 3, title: 'Close the Coalhouse Door', category: 'Drama', desc: 'This gritty musical about the coal industry in northeast England is regularly staged by all kinds of theatre companies, from professional to school to amateur. The play, adapted from stories by Sid Chaplin, and with the songs of Alex Glasgow, is frequently revived. It has been described as a hymn of unqualified praise to the miners who created a revolutionary weapon without having a revolutionary intent. Alan Plater has written numerous radio, television, theatre, and film scripts, as well as fiction.'},
  {id: 4, title: 'Three Really Nasty Plays', category: 'Drama', desc: 'Award-winning playwright Ron Chambers will stir your social consciousness in the compelling and really dastardly plays, Three Really Nasty Plays which won the Gwen Pharis Ringwood Award for Drama at the Alberta Book Awards.'},
  {id: 5, title: 'XOME the Ever Cheated!', category: 'Drama', desc: 'It is a drama aiming at female-male-equality. When they grew up, Radha and Vinod moved so closely that Radha\'s mother Bindu had to warn them. '},
  {id: 6, title: 'Upright Citizens Brigade Comedy Improvisation Manual', category: 'Comedy', desc: 'The Upright Citizens Brigade Comedy Improvisation Manual is a comprehensive guide to the UCB style of long form comedy improvisation. Written by UCB founding members Matt Besser, Ian Roberts, and Matt Walsh, the manual covers everything from the basics of two person scene work (with a heavy emphasis on finding "the game" of the scene), to the complexities of working within an ensemble to perform long form structures, such as "The Harold" and "The Movie".'},
  {id: 7, title: 'The Hidden Tools of Comedy: The Serious Business of Being Funny', category: 'Comedy', desc: 'While other books give you tips on how to “write funny,” this book offers a paradigm shift in understanding the mechanics and art of comedy, and the proven, practical tools that help writers translate that understanding into successful, commercial scripts. The Hidden Tools of Comedy unlocks the unique secrets and techniques of writing comedy. Kaplan deconstructs sequences in popular films and TV that work and don’t work, and explains what tools were used (or should have been used).'},
  {id: 8, title: 'Poking a Dead Frog: Conversations with Today’s Top Comedy Writers', category: 'Comedy', desc: 'Amy Poehler, Mel Brooks, Adam McKay, George Saunders, Bill Hader, Patton Oswalt, and many more take us deep inside the mysterious world of comedy in this fascinating, laugh-out-loud-funny book. Packed with behind-the-scenes stories—from a day in the writers’ room at The Onion to why a sketch does or doesn’t make it onto Saturday Night Live to how the BBC nearly erased the entire first season of Monty Python’s Flying Circus—Poking a Dead Frog is a must-read for comedy buffs, writers and pop culture junkies alike.'},
  {id: 9, title: 'Truth in Comedy: The Manual for Improvisation', category: 'Comedy', desc: 'Want to learn the improv techniques that helped Mike Myers, Chris Farley, John Belushi, and many others along the road to TV and film stardom? Then let two esteemed founders of long-form improvisational theatre, Del Close and Charna Halpern, teach you the "Harold." This groundbreaking acting exercise emphasizes pattern recognition and subversion of the audience s expectations, which are important factors for making people laugh without ever telling a joke. It involves six to seven players and many kinds of scenes: games, monologues, songs, skits and more, all of which are bound to keep both actors and audience members guessing. The Harold is non-linear entertainment that remembers everything and wastes nothing the key to successful improvising and has become a standard in comedy clubs and improv theatres around the globe.'},
  {id: 10, title: 'The Tao of Comedy: Embrace the Pause', category: 'Comedy', desc: 'There are a lot of stand-up comedy books out there. This book is like none of them. It is about the Art of Comedy, the Zen of Comedy, the Tao of Comedy. It is comedy from the soul instead of the head. It is about Ego-less comedy. Don’t Act. Be. You don’t do standup comedy; it does you.'},
  {id: 11, title: 'The Dangerous Book for Boys', category: 'Sport', desc: 'The classic bestselling book for every boy from eight to eighty, covering essential boyhood skills such as building tree houses*, learning how to fish, finding true north, and even answering the age-old question of what the big deal with girls is.'},
  {id: 12, title: 'Inside the Empire: The True Power Behind the New York Yankees', category: 'Sport', desc: 'Inside the Empire gives baseball fans a rare, behind-the-scenes look at the 2018 New York Yankees season. But more than just a clubhouse diary, the book is dead-on in its depiction of a general manager’s daily life and the many decisions that go into building a playoff team. Bob Klapisch and Paul Solotaroff’s combined experience and engaging writing style make this book a fantastic read for anyone who follows the game.'},
  {id: 13, title: 'The Mamba Mentality: How I Play', category: 'Sport', desc: 'The first book from the basketball superstar Kobe Bryant―a lavish, deep dive inside the mind of one of the most revered athletes of all time'},
  {id: 14, title: 'Horizon', category: 'Sport', desc: 'Taking us nearly from pole to pole--from modern megacities to some of the most remote regions on the earth--and across decades of lived experience, Barry Lopez, hailed by the Los Angeles Times Book Review as "one of our finest writers," gives us his most far-ranging yet personal work to date, in a book that moves indelibly, immersively, through his travels to six regions of the world: from Western Oregon to the High Arctic; from the Galápagos to the Kenyan desert; from Botany Bay in Australia to finally, unforgettably, the ice shelves of Antarctica.'},
];
